/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Body41
 */

public class Body41 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("icon_url")
  private String iconUrl = null;

  @SerializedName("callback_urls")
  private List<String> callbackUrls = new ArrayList<String>();

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("is_trusted")
  private Boolean isTrusted = null;

  public Body41 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the client application
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The id of the client application")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Body41 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the client application
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the client application")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Body41 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A short description of the application
   * @return description
  **/
  @ApiModelProperty(required = true, value = "A short description of the application")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Body41 iconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * A URL to an icon to display with the application
   * @return iconUrl
  **/
  @ApiModelProperty(value = "A URL to an icon to display with the application")
  public String getIconUrl() {
    return iconUrl;
  }

  public void setIconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
  }

  public Body41 callbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
    return this;
  }

  public Body41 addCallbackUrlsItem(String callbackUrlsItem) {
    this.callbackUrls.add(callbackUrlsItem);
    return this;
  }

   /**
   * A list of callback URLs for the appliation
   * @return callbackUrls
  **/
  @ApiModelProperty(required = true, value = "A list of callback URLs for the appliation")
  public List<String> getCallbackUrls() {
    return callbackUrls;
  }

  public void setCallbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
  }

  public Body41 homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * A link to the website of the application
   * @return homepage
  **/
  @ApiModelProperty(required = true, value = "A link to the website of the application")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public Body41 isTrusted(Boolean isTrusted) {
    this.isTrusted = isTrusted;
    return this;
  }

   /**
   * Set this to &#x60;true&#x60; to skip asking users for permission. It will be set to false if value is not provided.
   * @return isTrusted
  **/
  @ApiModelProperty(value = "Set this to `true` to skip asking users for permission. It will be set to false if value is not provided.")
  public Boolean isIsTrusted() {
    return isTrusted;
  }

  public void setIsTrusted(Boolean isTrusted) {
    this.isTrusted = isTrusted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body41 body41 = (Body41) o;
    return Objects.equals(this.id, body41.id) &&
        Objects.equals(this.name, body41.name) &&
        Objects.equals(this.description, body41.description) &&
        Objects.equals(this.iconUrl, body41.iconUrl) &&
        Objects.equals(this.callbackUrls, body41.callbackUrls) &&
        Objects.equals(this.homepage, body41.homepage) &&
        Objects.equals(this.isTrusted, body41.isTrusted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, iconUrl, callbackUrls, homepage, isTrusted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body41 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("    callbackUrls: ").append(toIndentedString(callbackUrls)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    isTrusted: ").append(toIndentedString(isTrusted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

