/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body6
 */

public class Body6 {
  @SerializedName("activate")
  private Boolean activate = null;

  @SerializedName("code")
  private String code = null;

  public Body6 activate(Boolean activate) {
    this.activate = activate;
    return this;
  }

   /**
   * Use &#x60;true&#x60; to activate, &#x60;false&#x60; to deactivate
   * @return activate
  **/
  @ApiModelProperty(required = true, value = "Use `true` to activate, `false` to deactivate")
  public Boolean isActivate() {
    return activate;
  }

  public void setActivate(Boolean activate) {
    this.activate = activate;
  }

  public Body6 code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code produced by your MFA client. Required if &#x60;activate&#x60; is true
   * @return code
  **/
  @ApiModelProperty(value = "The code produced by your MFA client. Required if `activate` is true")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body6 body6 = (Body6) o;
    return Objects.equals(this.activate, body6.activate) &&
        Objects.equals(this.code, body6.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activate, code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body6 {\n");
    
    sb.append("    activate: ").append(toIndentedString(activate)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

