/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body33
 */

public class Body33 {
  @SerializedName("term")
  private String term = null;

  @SerializedName("prefix_only")
  private String prefixOnly = null;

  public Body33 term(String term) {
    this.term = term;
    return this;
  }

   /**
   * The term to match against the emoji name.
   * @return term
  **/
  @ApiModelProperty(required = true, value = "The term to match against the emoji name.")
  public String getTerm() {
    return term;
  }

  public void setTerm(String term) {
    this.term = term;
  }

  public Body33 prefixOnly(String prefixOnly) {
    this.prefixOnly = prefixOnly;
    return this;
  }

   /**
   * Set to only search for names starting with the search term.
   * @return prefixOnly
  **/
  @ApiModelProperty(value = "Set to only search for names starting with the search term.")
  public String getPrefixOnly() {
    return prefixOnly;
  }

  public void setPrefixOnly(String prefixOnly) {
    this.prefixOnly = prefixOnly;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body33 body33 = (Body33) o;
    return Objects.equals(this.term, body33.term) &&
        Objects.equals(this.prefixOnly, body33.prefixOnly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(term, prefixOnly);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body33 {\n");
    
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    prefixOnly: ").append(toIndentedString(prefixOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

