/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body26
 */

public class Body26 {
  @SerializedName("user_id")
  private String userId = null;

  @SerializedName("post_root_id")
  private String postRootId = null;

  public Body26 userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The ID of user to add into the channel
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "The ID of user to add into the channel")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public Body26 postRootId(String postRootId) {
    this.postRootId = postRootId;
    return this;
  }

   /**
   * The ID of root post where link to add channel member originates
   * @return postRootId
  **/
  @ApiModelProperty(value = "The ID of root post where link to add channel member originates")
  public String getPostRootId() {
    return postRootId;
  }

  public void setPostRootId(String postRootId) {
    this.postRootId = postRootId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body26 body26 = (Body26) o;
    return Objects.equals(this.userId, body26.userId) &&
        Objects.equals(this.postRootId, body26.postRootId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, postRootId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body26 {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    postRootId: ").append(toIndentedString(postRootId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

