/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body17
 */

public class Body17 {
  @SerializedName("name")
  private String name = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("type")
  private String type = null;

  public Body17 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Unique handler for a team, will be present in the team URL
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Unique handler for a team, will be present in the team URL")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Body17 displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Non-unique UI name for the team
   * @return displayName
  **/
  @ApiModelProperty(required = true, value = "Non-unique UI name for the team")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Body17 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * &#x60;&#39;O&#39;&#x60; for open, &#x60;&#39;I&#39;&#x60; for invite only
   * @return type
  **/
  @ApiModelProperty(required = true, value = "`'O'` for open, `'I'` for invite only")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body17 body17 = (Body17) o;
    return Objects.equals(this.name, body17.name) &&
        Objects.equals(this.displayName, body17.displayName) &&
        Objects.equals(this.type, body17.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayName, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body17 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

