/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body34
 */

public class Body34 {
  @SerializedName("channel_id")
  private String channelId = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("icon_url")
  private String iconUrl = null;

  public Body34 channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID of a public channel or private group that receives the webhook payloads.
   * @return channelId
  **/
  @ApiModelProperty(required = true, value = "The ID of a public channel or private group that receives the webhook payloads.")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public Body34 displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name for this incoming webhook
   * @return displayName
  **/
  @ApiModelProperty(value = "The display name for this incoming webhook")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Body34 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description for this incoming webhook
   * @return description
  **/
  @ApiModelProperty(value = "The description for this incoming webhook")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Body34 username(String username) {
    this.username = username;
    return this;
  }

   /**
   * The username this incoming webhook will post as.
   * @return username
  **/
  @ApiModelProperty(value = "The username this incoming webhook will post as.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public Body34 iconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * The profile picture this incoming webhook will use when posting.
   * @return iconUrl
  **/
  @ApiModelProperty(value = "The profile picture this incoming webhook will use when posting.")
  public String getIconUrl() {
    return iconUrl;
  }

  public void setIconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body34 body34 = (Body34) o;
    return Objects.equals(this.channelId, body34.channelId) &&
        Objects.equals(this.displayName, body34.displayName) &&
        Objects.equals(this.description, body34.description) &&
        Objects.equals(this.username, body34.username) &&
        Objects.equals(this.iconUrl, body34.iconUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, displayName, description, username, iconUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body34 {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

