/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body18
 */

public class Body18 {
  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("company_name")
  private String companyName = null;

  @SerializedName("allowed_domains")
  private String allowedDomains = null;

  @SerializedName("invite_id")
  private String inviteId = null;

  @SerializedName("allow_open_invite")
  private String allowOpenInvite = null;

  public Body18 displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Body18 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Body18 companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public Body18 allowedDomains(String allowedDomains) {
    this.allowedDomains = allowedDomains;
    return this;
  }

   /**
   * Get allowedDomains
   * @return allowedDomains
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAllowedDomains() {
    return allowedDomains;
  }

  public void setAllowedDomains(String allowedDomains) {
    this.allowedDomains = allowedDomains;
  }

  public Body18 inviteId(String inviteId) {
    this.inviteId = inviteId;
    return this;
  }

   /**
   * Get inviteId
   * @return inviteId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getInviteId() {
    return inviteId;
  }

  public void setInviteId(String inviteId) {
    this.inviteId = inviteId;
  }

  public Body18 allowOpenInvite(String allowOpenInvite) {
    this.allowOpenInvite = allowOpenInvite;
    return this;
  }

   /**
   * Get allowOpenInvite
   * @return allowOpenInvite
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAllowOpenInvite() {
    return allowOpenInvite;
  }

  public void setAllowOpenInvite(String allowOpenInvite) {
    this.allowOpenInvite = allowOpenInvite;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body18 body18 = (Body18) o;
    return Objects.equals(this.displayName, body18.displayName) &&
        Objects.equals(this.description, body18.description) &&
        Objects.equals(this.companyName, body18.companyName) &&
        Objects.equals(this.allowedDomains, body18.allowedDomains) &&
        Objects.equals(this.inviteId, body18.inviteId) &&
        Objects.equals(this.allowOpenInvite, body18.allowOpenInvite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, description, companyName, allowedDomains, inviteId, allowOpenInvite);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body18 {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    allowedDomains: ").append(toIndentedString(allowedDomains)).append("\n");
    sb.append("    inviteId: ").append(toIndentedString(inviteId)).append("\n");
    sb.append("    allowOpenInvite: ").append(toIndentedString(allowOpenInvite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

