/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChannelNotifyProps;
import java.io.IOException;

/**
 * ChannelMember
 */

public class ChannelMember {
  @SerializedName("channel_id")
  private String channelId = null;

  @SerializedName("user_id")
  private String userId = null;

  @SerializedName("roles")
  private String roles = null;

  @SerializedName("last_viewed_at")
  private Integer lastViewedAt = null;

  @SerializedName("msg_count")
  private Integer msgCount = null;

  @SerializedName("mention_count")
  private Integer mentionCount = null;

  @SerializedName("notify_props")
  private ChannelNotifyProps notifyProps = null;

  @SerializedName("last_update_at")
  private Integer lastUpdateAt = null;

  public ChannelMember channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * Get channelId
   * @return channelId
  **/
  @ApiModelProperty(value = "")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public ChannelMember userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public ChannelMember roles(String roles) {
    this.roles = roles;
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public String getRoles() {
    return roles;
  }

  public void setRoles(String roles) {
    this.roles = roles;
  }

  public ChannelMember lastViewedAt(Integer lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
    return this;
  }

   /**
   * Get lastViewedAt
   * @return lastViewedAt
  **/
  @ApiModelProperty(value = "")
  public Integer getLastViewedAt() {
    return lastViewedAt;
  }

  public void setLastViewedAt(Integer lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
  }

  public ChannelMember msgCount(Integer msgCount) {
    this.msgCount = msgCount;
    return this;
  }

   /**
   * Get msgCount
   * @return msgCount
  **/
  @ApiModelProperty(value = "")
  public Integer getMsgCount() {
    return msgCount;
  }

  public void setMsgCount(Integer msgCount) {
    this.msgCount = msgCount;
  }

  public ChannelMember mentionCount(Integer mentionCount) {
    this.mentionCount = mentionCount;
    return this;
  }

   /**
   * Get mentionCount
   * @return mentionCount
  **/
  @ApiModelProperty(value = "")
  public Integer getMentionCount() {
    return mentionCount;
  }

  public void setMentionCount(Integer mentionCount) {
    this.mentionCount = mentionCount;
  }

  public ChannelMember notifyProps(ChannelNotifyProps notifyProps) {
    this.notifyProps = notifyProps;
    return this;
  }

   /**
   * Field only visible to self and admins
   * @return notifyProps
  **/
  @ApiModelProperty(value = "Field only visible to self and admins")
  public ChannelNotifyProps getNotifyProps() {
    return notifyProps;
  }

  public void setNotifyProps(ChannelNotifyProps notifyProps) {
    this.notifyProps = notifyProps;
  }

  public ChannelMember lastUpdateAt(Integer lastUpdateAt) {
    this.lastUpdateAt = lastUpdateAt;
    return this;
  }

   /**
   * Get lastUpdateAt
   * @return lastUpdateAt
  **/
  @ApiModelProperty(value = "")
  public Integer getLastUpdateAt() {
    return lastUpdateAt;
  }

  public void setLastUpdateAt(Integer lastUpdateAt) {
    this.lastUpdateAt = lastUpdateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelMember channelMember = (ChannelMember) o;
    return Objects.equals(this.channelId, channelMember.channelId) &&
        Objects.equals(this.userId, channelMember.userId) &&
        Objects.equals(this.roles, channelMember.roles) &&
        Objects.equals(this.lastViewedAt, channelMember.lastViewedAt) &&
        Objects.equals(this.msgCount, channelMember.msgCount) &&
        Objects.equals(this.mentionCount, channelMember.mentionCount) &&
        Objects.equals(this.notifyProps, channelMember.notifyProps) &&
        Objects.equals(this.lastUpdateAt, channelMember.lastUpdateAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, userId, roles, lastViewedAt, msgCount, mentionCount, notifyProps, lastUpdateAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelMember {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    lastViewedAt: ").append(toIndentedString(lastViewedAt)).append("\n");
    sb.append("    msgCount: ").append(toIndentedString(msgCount)).append("\n");
    sb.append("    mentionCount: ").append(toIndentedString(mentionCount)).append("\n");
    sb.append("    notifyProps: ").append(toIndentedString(notifyProps)).append("\n");
    sb.append("    lastUpdateAt: ").append(toIndentedString(lastUpdateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

