/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigLdapSettings
 */

public class ConfigLdapSettings {
  @SerializedName("Enable")
  private Boolean enable = null;

  @SerializedName("LdapServer")
  private String ldapServer = null;

  @SerializedName("LdapPort")
  private Integer ldapPort = null;

  @SerializedName("ConnectionSecurity")
  private String connectionSecurity = null;

  @SerializedName("BaseDN")
  private String baseDN = null;

  @SerializedName("BindUsername")
  private String bindUsername = null;

  @SerializedName("BindPassword")
  private String bindPassword = null;

  @SerializedName("UserFilter")
  private String userFilter = null;

  @SerializedName("FirstNameAttribute")
  private String firstNameAttribute = null;

  @SerializedName("LastNameAttribute")
  private String lastNameAttribute = null;

  @SerializedName("EmailAttribute")
  private String emailAttribute = null;

  @SerializedName("UsernameAttribute")
  private String usernameAttribute = null;

  @SerializedName("NicknameAttribute")
  private String nicknameAttribute = null;

  @SerializedName("IdAttribute")
  private String idAttribute = null;

  @SerializedName("PositionAttribute")
  private String positionAttribute = null;

  @SerializedName("SyncIntervalMinutes")
  private Integer syncIntervalMinutes = null;

  @SerializedName("SkipCertificateVerification")
  private Boolean skipCertificateVerification = null;

  @SerializedName("QueryTimeout")
  private Integer queryTimeout = null;

  @SerializedName("MaxPageSize")
  private Integer maxPageSize = null;

  @SerializedName("LoginFieldName")
  private String loginFieldName = null;

  public ConfigLdapSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public ConfigLdapSettings ldapServer(String ldapServer) {
    this.ldapServer = ldapServer;
    return this;
  }

   /**
   * Get ldapServer
   * @return ldapServer
  **/
  @ApiModelProperty(value = "")
  public String getLdapServer() {
    return ldapServer;
  }

  public void setLdapServer(String ldapServer) {
    this.ldapServer = ldapServer;
  }

  public ConfigLdapSettings ldapPort(Integer ldapPort) {
    this.ldapPort = ldapPort;
    return this;
  }

   /**
   * Get ldapPort
   * @return ldapPort
  **/
  @ApiModelProperty(value = "")
  public Integer getLdapPort() {
    return ldapPort;
  }

  public void setLdapPort(Integer ldapPort) {
    this.ldapPort = ldapPort;
  }

  public ConfigLdapSettings connectionSecurity(String connectionSecurity) {
    this.connectionSecurity = connectionSecurity;
    return this;
  }

   /**
   * Get connectionSecurity
   * @return connectionSecurity
  **/
  @ApiModelProperty(value = "")
  public String getConnectionSecurity() {
    return connectionSecurity;
  }

  public void setConnectionSecurity(String connectionSecurity) {
    this.connectionSecurity = connectionSecurity;
  }

  public ConfigLdapSettings baseDN(String baseDN) {
    this.baseDN = baseDN;
    return this;
  }

   /**
   * Get baseDN
   * @return baseDN
  **/
  @ApiModelProperty(value = "")
  public String getBaseDN() {
    return baseDN;
  }

  public void setBaseDN(String baseDN) {
    this.baseDN = baseDN;
  }

  public ConfigLdapSettings bindUsername(String bindUsername) {
    this.bindUsername = bindUsername;
    return this;
  }

   /**
   * Get bindUsername
   * @return bindUsername
  **/
  @ApiModelProperty(value = "")
  public String getBindUsername() {
    return bindUsername;
  }

  public void setBindUsername(String bindUsername) {
    this.bindUsername = bindUsername;
  }

  public ConfigLdapSettings bindPassword(String bindPassword) {
    this.bindPassword = bindPassword;
    return this;
  }

   /**
   * Get bindPassword
   * @return bindPassword
  **/
  @ApiModelProperty(value = "")
  public String getBindPassword() {
    return bindPassword;
  }

  public void setBindPassword(String bindPassword) {
    this.bindPassword = bindPassword;
  }

  public ConfigLdapSettings userFilter(String userFilter) {
    this.userFilter = userFilter;
    return this;
  }

   /**
   * Get userFilter
   * @return userFilter
  **/
  @ApiModelProperty(value = "")
  public String getUserFilter() {
    return userFilter;
  }

  public void setUserFilter(String userFilter) {
    this.userFilter = userFilter;
  }

  public ConfigLdapSettings firstNameAttribute(String firstNameAttribute) {
    this.firstNameAttribute = firstNameAttribute;
    return this;
  }

   /**
   * Get firstNameAttribute
   * @return firstNameAttribute
  **/
  @ApiModelProperty(value = "")
  public String getFirstNameAttribute() {
    return firstNameAttribute;
  }

  public void setFirstNameAttribute(String firstNameAttribute) {
    this.firstNameAttribute = firstNameAttribute;
  }

  public ConfigLdapSettings lastNameAttribute(String lastNameAttribute) {
    this.lastNameAttribute = lastNameAttribute;
    return this;
  }

   /**
   * Get lastNameAttribute
   * @return lastNameAttribute
  **/
  @ApiModelProperty(value = "")
  public String getLastNameAttribute() {
    return lastNameAttribute;
  }

  public void setLastNameAttribute(String lastNameAttribute) {
    this.lastNameAttribute = lastNameAttribute;
  }

  public ConfigLdapSettings emailAttribute(String emailAttribute) {
    this.emailAttribute = emailAttribute;
    return this;
  }

   /**
   * Get emailAttribute
   * @return emailAttribute
  **/
  @ApiModelProperty(value = "")
  public String getEmailAttribute() {
    return emailAttribute;
  }

  public void setEmailAttribute(String emailAttribute) {
    this.emailAttribute = emailAttribute;
  }

  public ConfigLdapSettings usernameAttribute(String usernameAttribute) {
    this.usernameAttribute = usernameAttribute;
    return this;
  }

   /**
   * Get usernameAttribute
   * @return usernameAttribute
  **/
  @ApiModelProperty(value = "")
  public String getUsernameAttribute() {
    return usernameAttribute;
  }

  public void setUsernameAttribute(String usernameAttribute) {
    this.usernameAttribute = usernameAttribute;
  }

  public ConfigLdapSettings nicknameAttribute(String nicknameAttribute) {
    this.nicknameAttribute = nicknameAttribute;
    return this;
  }

   /**
   * Get nicknameAttribute
   * @return nicknameAttribute
  **/
  @ApiModelProperty(value = "")
  public String getNicknameAttribute() {
    return nicknameAttribute;
  }

  public void setNicknameAttribute(String nicknameAttribute) {
    this.nicknameAttribute = nicknameAttribute;
  }

  public ConfigLdapSettings idAttribute(String idAttribute) {
    this.idAttribute = idAttribute;
    return this;
  }

   /**
   * Get idAttribute
   * @return idAttribute
  **/
  @ApiModelProperty(value = "")
  public String getIdAttribute() {
    return idAttribute;
  }

  public void setIdAttribute(String idAttribute) {
    this.idAttribute = idAttribute;
  }

  public ConfigLdapSettings positionAttribute(String positionAttribute) {
    this.positionAttribute = positionAttribute;
    return this;
  }

   /**
   * Get positionAttribute
   * @return positionAttribute
  **/
  @ApiModelProperty(value = "")
  public String getPositionAttribute() {
    return positionAttribute;
  }

  public void setPositionAttribute(String positionAttribute) {
    this.positionAttribute = positionAttribute;
  }

  public ConfigLdapSettings syncIntervalMinutes(Integer syncIntervalMinutes) {
    this.syncIntervalMinutes = syncIntervalMinutes;
    return this;
  }

   /**
   * Get syncIntervalMinutes
   * @return syncIntervalMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getSyncIntervalMinutes() {
    return syncIntervalMinutes;
  }

  public void setSyncIntervalMinutes(Integer syncIntervalMinutes) {
    this.syncIntervalMinutes = syncIntervalMinutes;
  }

  public ConfigLdapSettings skipCertificateVerification(Boolean skipCertificateVerification) {
    this.skipCertificateVerification = skipCertificateVerification;
    return this;
  }

   /**
   * Get skipCertificateVerification
   * @return skipCertificateVerification
  **/
  @ApiModelProperty(value = "")
  public Boolean isSkipCertificateVerification() {
    return skipCertificateVerification;
  }

  public void setSkipCertificateVerification(Boolean skipCertificateVerification) {
    this.skipCertificateVerification = skipCertificateVerification;
  }

  public ConfigLdapSettings queryTimeout(Integer queryTimeout) {
    this.queryTimeout = queryTimeout;
    return this;
  }

   /**
   * Get queryTimeout
   * @return queryTimeout
  **/
  @ApiModelProperty(value = "")
  public Integer getQueryTimeout() {
    return queryTimeout;
  }

  public void setQueryTimeout(Integer queryTimeout) {
    this.queryTimeout = queryTimeout;
  }

  public ConfigLdapSettings maxPageSize(Integer maxPageSize) {
    this.maxPageSize = maxPageSize;
    return this;
  }

   /**
   * Get maxPageSize
   * @return maxPageSize
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxPageSize() {
    return maxPageSize;
  }

  public void setMaxPageSize(Integer maxPageSize) {
    this.maxPageSize = maxPageSize;
  }

  public ConfigLdapSettings loginFieldName(String loginFieldName) {
    this.loginFieldName = loginFieldName;
    return this;
  }

   /**
   * Get loginFieldName
   * @return loginFieldName
  **/
  @ApiModelProperty(value = "")
  public String getLoginFieldName() {
    return loginFieldName;
  }

  public void setLoginFieldName(String loginFieldName) {
    this.loginFieldName = loginFieldName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigLdapSettings configLdapSettings = (ConfigLdapSettings) o;
    return Objects.equals(this.enable, configLdapSettings.enable) &&
        Objects.equals(this.ldapServer, configLdapSettings.ldapServer) &&
        Objects.equals(this.ldapPort, configLdapSettings.ldapPort) &&
        Objects.equals(this.connectionSecurity, configLdapSettings.connectionSecurity) &&
        Objects.equals(this.baseDN, configLdapSettings.baseDN) &&
        Objects.equals(this.bindUsername, configLdapSettings.bindUsername) &&
        Objects.equals(this.bindPassword, configLdapSettings.bindPassword) &&
        Objects.equals(this.userFilter, configLdapSettings.userFilter) &&
        Objects.equals(this.firstNameAttribute, configLdapSettings.firstNameAttribute) &&
        Objects.equals(this.lastNameAttribute, configLdapSettings.lastNameAttribute) &&
        Objects.equals(this.emailAttribute, configLdapSettings.emailAttribute) &&
        Objects.equals(this.usernameAttribute, configLdapSettings.usernameAttribute) &&
        Objects.equals(this.nicknameAttribute, configLdapSettings.nicknameAttribute) &&
        Objects.equals(this.idAttribute, configLdapSettings.idAttribute) &&
        Objects.equals(this.positionAttribute, configLdapSettings.positionAttribute) &&
        Objects.equals(this.syncIntervalMinutes, configLdapSettings.syncIntervalMinutes) &&
        Objects.equals(this.skipCertificateVerification, configLdapSettings.skipCertificateVerification) &&
        Objects.equals(this.queryTimeout, configLdapSettings.queryTimeout) &&
        Objects.equals(this.maxPageSize, configLdapSettings.maxPageSize) &&
        Objects.equals(this.loginFieldName, configLdapSettings.loginFieldName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, ldapServer, ldapPort, connectionSecurity, baseDN, bindUsername, bindPassword, userFilter, firstNameAttribute, lastNameAttribute, emailAttribute, usernameAttribute, nicknameAttribute, idAttribute, positionAttribute, syncIntervalMinutes, skipCertificateVerification, queryTimeout, maxPageSize, loginFieldName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigLdapSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    ldapServer: ").append(toIndentedString(ldapServer)).append("\n");
    sb.append("    ldapPort: ").append(toIndentedString(ldapPort)).append("\n");
    sb.append("    connectionSecurity: ").append(toIndentedString(connectionSecurity)).append("\n");
    sb.append("    baseDN: ").append(toIndentedString(baseDN)).append("\n");
    sb.append("    bindUsername: ").append(toIndentedString(bindUsername)).append("\n");
    sb.append("    bindPassword: ").append(toIndentedString(bindPassword)).append("\n");
    sb.append("    userFilter: ").append(toIndentedString(userFilter)).append("\n");
    sb.append("    firstNameAttribute: ").append(toIndentedString(firstNameAttribute)).append("\n");
    sb.append("    lastNameAttribute: ").append(toIndentedString(lastNameAttribute)).append("\n");
    sb.append("    emailAttribute: ").append(toIndentedString(emailAttribute)).append("\n");
    sb.append("    usernameAttribute: ").append(toIndentedString(usernameAttribute)).append("\n");
    sb.append("    nicknameAttribute: ").append(toIndentedString(nicknameAttribute)).append("\n");
    sb.append("    idAttribute: ").append(toIndentedString(idAttribute)).append("\n");
    sb.append("    positionAttribute: ").append(toIndentedString(positionAttribute)).append("\n");
    sb.append("    syncIntervalMinutes: ").append(toIndentedString(syncIntervalMinutes)).append("\n");
    sb.append("    skipCertificateVerification: ").append(toIndentedString(skipCertificateVerification)).append("\n");
    sb.append("    queryTimeout: ").append(toIndentedString(queryTimeout)).append("\n");
    sb.append("    maxPageSize: ").append(toIndentedString(maxPageSize)).append("\n");
    sb.append("    loginFieldName: ").append(toIndentedString(loginFieldName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

