/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ConfigSqlSettings
 */

public class ConfigSqlSettings {
  @SerializedName("DriverName")
  private String driverName = null;

  @SerializedName("DataSource")
  private String dataSource = null;

  @SerializedName("DataSourceReplicas")
  private List<String> dataSourceReplicas = null;

  @SerializedName("MaxIdleConns")
  private Integer maxIdleConns = null;

  @SerializedName("MaxOpenConns")
  private Integer maxOpenConns = null;

  @SerializedName("Trace")
  private Boolean trace = null;

  @SerializedName("AtRestEncryptKey")
  private String atRestEncryptKey = null;

  public ConfigSqlSettings driverName(String driverName) {
    this.driverName = driverName;
    return this;
  }

   /**
   * Get driverName
   * @return driverName
  **/
  @ApiModelProperty(value = "")
  public String getDriverName() {
    return driverName;
  }

  public void setDriverName(String driverName) {
    this.driverName = driverName;
  }

  public ConfigSqlSettings dataSource(String dataSource) {
    this.dataSource = dataSource;
    return this;
  }

   /**
   * Get dataSource
   * @return dataSource
  **/
  @ApiModelProperty(value = "")
  public String getDataSource() {
    return dataSource;
  }

  public void setDataSource(String dataSource) {
    this.dataSource = dataSource;
  }

  public ConfigSqlSettings dataSourceReplicas(List<String> dataSourceReplicas) {
    this.dataSourceReplicas = dataSourceReplicas;
    return this;
  }

  public ConfigSqlSettings addDataSourceReplicasItem(String dataSourceReplicasItem) {
    if (this.dataSourceReplicas == null) {
      this.dataSourceReplicas = new ArrayList<String>();
    }
    this.dataSourceReplicas.add(dataSourceReplicasItem);
    return this;
  }

   /**
   * Get dataSourceReplicas
   * @return dataSourceReplicas
  **/
  @ApiModelProperty(value = "")
  public List<String> getDataSourceReplicas() {
    return dataSourceReplicas;
  }

  public void setDataSourceReplicas(List<String> dataSourceReplicas) {
    this.dataSourceReplicas = dataSourceReplicas;
  }

  public ConfigSqlSettings maxIdleConns(Integer maxIdleConns) {
    this.maxIdleConns = maxIdleConns;
    return this;
  }

   /**
   * Get maxIdleConns
   * @return maxIdleConns
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxIdleConns() {
    return maxIdleConns;
  }

  public void setMaxIdleConns(Integer maxIdleConns) {
    this.maxIdleConns = maxIdleConns;
  }

  public ConfigSqlSettings maxOpenConns(Integer maxOpenConns) {
    this.maxOpenConns = maxOpenConns;
    return this;
  }

   /**
   * Get maxOpenConns
   * @return maxOpenConns
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxOpenConns() {
    return maxOpenConns;
  }

  public void setMaxOpenConns(Integer maxOpenConns) {
    this.maxOpenConns = maxOpenConns;
  }

  public ConfigSqlSettings trace(Boolean trace) {
    this.trace = trace;
    return this;
  }

   /**
   * Get trace
   * @return trace
  **/
  @ApiModelProperty(value = "")
  public Boolean isTrace() {
    return trace;
  }

  public void setTrace(Boolean trace) {
    this.trace = trace;
  }

  public ConfigSqlSettings atRestEncryptKey(String atRestEncryptKey) {
    this.atRestEncryptKey = atRestEncryptKey;
    return this;
  }

   /**
   * Get atRestEncryptKey
   * @return atRestEncryptKey
  **/
  @ApiModelProperty(value = "")
  public String getAtRestEncryptKey() {
    return atRestEncryptKey;
  }

  public void setAtRestEncryptKey(String atRestEncryptKey) {
    this.atRestEncryptKey = atRestEncryptKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigSqlSettings configSqlSettings = (ConfigSqlSettings) o;
    return Objects.equals(this.driverName, configSqlSettings.driverName) &&
        Objects.equals(this.dataSource, configSqlSettings.dataSource) &&
        Objects.equals(this.dataSourceReplicas, configSqlSettings.dataSourceReplicas) &&
        Objects.equals(this.maxIdleConns, configSqlSettings.maxIdleConns) &&
        Objects.equals(this.maxOpenConns, configSqlSettings.maxOpenConns) &&
        Objects.equals(this.trace, configSqlSettings.trace) &&
        Objects.equals(this.atRestEncryptKey, configSqlSettings.atRestEncryptKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(driverName, dataSource, dataSourceReplicas, maxIdleConns, maxOpenConns, trace, atRestEncryptKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigSqlSettings {\n");
    
    sb.append("    driverName: ").append(toIndentedString(driverName)).append("\n");
    sb.append("    dataSource: ").append(toIndentedString(dataSource)).append("\n");
    sb.append("    dataSourceReplicas: ").append(toIndentedString(dataSourceReplicas)).append("\n");
    sb.append("    maxIdleConns: ").append(toIndentedString(maxIdleConns)).append("\n");
    sb.append("    maxOpenConns: ").append(toIndentedString(maxOpenConns)).append("\n");
    sb.append("    trace: ").append(toIndentedString(trace)).append("\n");
    sb.append("    atRestEncryptKey: ").append(toIndentedString(atRestEncryptKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

