/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigRateLimitSettings
 */

public class ConfigRateLimitSettings {
  @SerializedName("Enable")
  private Boolean enable = null;

  @SerializedName("PerSec")
  private Integer perSec = null;

  @SerializedName("MaxBurst")
  private Integer maxBurst = null;

  @SerializedName("MemoryStoreSize")
  private Integer memoryStoreSize = null;

  @SerializedName("VaryByRemoteAddr")
  private Boolean varyByRemoteAddr = null;

  @SerializedName("VaryByHeader")
  private String varyByHeader = null;

  public ConfigRateLimitSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public ConfigRateLimitSettings perSec(Integer perSec) {
    this.perSec = perSec;
    return this;
  }

   /**
   * Get perSec
   * @return perSec
  **/
  @ApiModelProperty(value = "")
  public Integer getPerSec() {
    return perSec;
  }

  public void setPerSec(Integer perSec) {
    this.perSec = perSec;
  }

  public ConfigRateLimitSettings maxBurst(Integer maxBurst) {
    this.maxBurst = maxBurst;
    return this;
  }

   /**
   * Get maxBurst
   * @return maxBurst
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxBurst() {
    return maxBurst;
  }

  public void setMaxBurst(Integer maxBurst) {
    this.maxBurst = maxBurst;
  }

  public ConfigRateLimitSettings memoryStoreSize(Integer memoryStoreSize) {
    this.memoryStoreSize = memoryStoreSize;
    return this;
  }

   /**
   * Get memoryStoreSize
   * @return memoryStoreSize
  **/
  @ApiModelProperty(value = "")
  public Integer getMemoryStoreSize() {
    return memoryStoreSize;
  }

  public void setMemoryStoreSize(Integer memoryStoreSize) {
    this.memoryStoreSize = memoryStoreSize;
  }

  public ConfigRateLimitSettings varyByRemoteAddr(Boolean varyByRemoteAddr) {
    this.varyByRemoteAddr = varyByRemoteAddr;
    return this;
  }

   /**
   * Get varyByRemoteAddr
   * @return varyByRemoteAddr
  **/
  @ApiModelProperty(value = "")
  public Boolean isVaryByRemoteAddr() {
    return varyByRemoteAddr;
  }

  public void setVaryByRemoteAddr(Boolean varyByRemoteAddr) {
    this.varyByRemoteAddr = varyByRemoteAddr;
  }

  public ConfigRateLimitSettings varyByHeader(String varyByHeader) {
    this.varyByHeader = varyByHeader;
    return this;
  }

   /**
   * Get varyByHeader
   * @return varyByHeader
  **/
  @ApiModelProperty(value = "")
  public String getVaryByHeader() {
    return varyByHeader;
  }

  public void setVaryByHeader(String varyByHeader) {
    this.varyByHeader = varyByHeader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigRateLimitSettings configRateLimitSettings = (ConfigRateLimitSettings) o;
    return Objects.equals(this.enable, configRateLimitSettings.enable) &&
        Objects.equals(this.perSec, configRateLimitSettings.perSec) &&
        Objects.equals(this.maxBurst, configRateLimitSettings.maxBurst) &&
        Objects.equals(this.memoryStoreSize, configRateLimitSettings.memoryStoreSize) &&
        Objects.equals(this.varyByRemoteAddr, configRateLimitSettings.varyByRemoteAddr) &&
        Objects.equals(this.varyByHeader, configRateLimitSettings.varyByHeader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, perSec, maxBurst, memoryStoreSize, varyByRemoteAddr, varyByHeader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigRateLimitSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    perSec: ").append(toIndentedString(perSec)).append("\n");
    sb.append("    maxBurst: ").append(toIndentedString(maxBurst)).append("\n");
    sb.append("    memoryStoreSize: ").append(toIndentedString(memoryStoreSize)).append("\n");
    sb.append("    varyByRemoteAddr: ").append(toIndentedString(varyByRemoteAddr)).append("\n");
    sb.append("    varyByHeader: ").append(toIndentedString(varyByHeader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

