/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigPrivacySettings
 */

public class ConfigPrivacySettings {
  @SerializedName("ShowEmailAddress")
  private Boolean showEmailAddress = null;

  @SerializedName("ShowFullName")
  private Boolean showFullName = null;

  public ConfigPrivacySettings showEmailAddress(Boolean showEmailAddress) {
    this.showEmailAddress = showEmailAddress;
    return this;
  }

   /**
   * Get showEmailAddress
   * @return showEmailAddress
  **/
  @ApiModelProperty(value = "")
  public Boolean isShowEmailAddress() {
    return showEmailAddress;
  }

  public void setShowEmailAddress(Boolean showEmailAddress) {
    this.showEmailAddress = showEmailAddress;
  }

  public ConfigPrivacySettings showFullName(Boolean showFullName) {
    this.showFullName = showFullName;
    return this;
  }

   /**
   * Get showFullName
   * @return showFullName
  **/
  @ApiModelProperty(value = "")
  public Boolean isShowFullName() {
    return showFullName;
  }

  public void setShowFullName(Boolean showFullName) {
    this.showFullName = showFullName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigPrivacySettings configPrivacySettings = (ConfigPrivacySettings) o;
    return Objects.equals(this.showEmailAddress, configPrivacySettings.showEmailAddress) &&
        Objects.equals(this.showFullName, configPrivacySettings.showFullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(showEmailAddress, showFullName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigPrivacySettings {\n");
    
    sb.append("    showEmailAddress: ").append(toIndentedString(showEmailAddress)).append("\n");
    sb.append("    showFullName: ").append(toIndentedString(showFullName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

