/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigComplianceSettings
 */

public class ConfigComplianceSettings {
  @SerializedName("Enable")
  private Boolean enable = null;

  @SerializedName("Directory")
  private String directory = null;

  @SerializedName("EnableDaily")
  private Boolean enableDaily = null;

  public ConfigComplianceSettings enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public ConfigComplianceSettings directory(String directory) {
    this.directory = directory;
    return this;
  }

   /**
   * Get directory
   * @return directory
  **/
  @ApiModelProperty(value = "")
  public String getDirectory() {
    return directory;
  }

  public void setDirectory(String directory) {
    this.directory = directory;
  }

  public ConfigComplianceSettings enableDaily(Boolean enableDaily) {
    this.enableDaily = enableDaily;
    return this;
  }

   /**
   * Get enableDaily
   * @return enableDaily
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnableDaily() {
    return enableDaily;
  }

  public void setEnableDaily(Boolean enableDaily) {
    this.enableDaily = enableDaily;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigComplianceSettings configComplianceSettings = (ConfigComplianceSettings) o;
    return Objects.equals(this.enable, configComplianceSettings.enable) &&
        Objects.equals(this.directory, configComplianceSettings.directory) &&
        Objects.equals(this.enableDaily, configComplianceSettings.enableDaily);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, directory, enableDaily);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigComplianceSettings {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("    enableDaily: ").append(toIndentedString(enableDaily)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

