/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2001
 */

public class InlineResponse2001 {
  @SerializedName("mfa_required")
  private Boolean mfaRequired = null;

  public InlineResponse2001 mfaRequired(Boolean mfaRequired) {
    this.mfaRequired = mfaRequired;
    return this;
  }

   /**
   * Value will &#x60;true&#x60; if MFA is active, &#x60;false&#x60; otherwise
   * @return mfaRequired
  **/
  @ApiModelProperty(value = "Value will `true` if MFA is active, `false` otherwise")
  public Boolean isMfaRequired() {
    return mfaRequired;
  }

  public void setMfaRequired(Boolean mfaRequired) {
    this.mfaRequired = mfaRequired;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.mfaRequired, inlineResponse2001.mfaRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mfaRequired);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    mfaRequired: ").append(toIndentedString(mfaRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

