/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2005
 */

public class InlineResponse2005 {
  @SerializedName("status")
  private String status = null;

  @SerializedName("last_viewed_at_times")
  private Object lastViewedAtTimes = null;

  public InlineResponse2005 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Value should be \&quot;OK\&quot; if successful
   * @return status
  **/
  @ApiModelProperty(value = "Value should be \"OK\" if successful")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse2005 lastViewedAtTimes(Object lastViewedAtTimes) {
    this.lastViewedAtTimes = lastViewedAtTimes;
    return this;
  }

   /**
   * A JSON object mapping channel IDs to the channel view times
   * @return lastViewedAtTimes
  **/
  @ApiModelProperty(value = "A JSON object mapping channel IDs to the channel view times")
  public Object getLastViewedAtTimes() {
    return lastViewedAtTimes;
  }

  public void setLastViewedAtTimes(Object lastViewedAtTimes) {
    this.lastViewedAtTimes = lastViewedAtTimes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.status, inlineResponse2005.status) &&
        Objects.equals(this.lastViewedAtTimes, inlineResponse2005.lastViewedAtTimes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, lastViewedAtTimes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastViewedAtTimes: ").append(toIndentedString(lastViewedAtTimes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

