/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Job
 */

public class Job {
  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("start_at")
  private Integer startAt = null;

  @SerializedName("last_activity_at")
  private Integer lastActivityAt = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("progress")
  private Integer progress = null;

  @SerializedName("data")
  private Object data = null;

  public Job id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique id of the job
   * @return id
  **/
  @ApiModelProperty(value = "The unique id of the job")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Job type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of job
   * @return type
  **/
  @ApiModelProperty(value = "The type of job")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Job createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time at which the job was created
   * @return createAt
  **/
  @ApiModelProperty(value = "The time at which the job was created")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public Job startAt(Integer startAt) {
    this.startAt = startAt;
    return this;
  }

   /**
   * The time at which the job was started
   * @return startAt
  **/
  @ApiModelProperty(value = "The time at which the job was started")
  public Integer getStartAt() {
    return startAt;
  }

  public void setStartAt(Integer startAt) {
    this.startAt = startAt;
  }

  public Job lastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
    return this;
  }

   /**
   * The last time at which the job had activity
   * @return lastActivityAt
  **/
  @ApiModelProperty(value = "The last time at which the job had activity")
  public Integer getLastActivityAt() {
    return lastActivityAt;
  }

  public void setLastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
  }

  public Job status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the job
   * @return status
  **/
  @ApiModelProperty(value = "The status of the job")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Job progress(Integer progress) {
    this.progress = progress;
    return this;
  }

   /**
   * The progress (as a percentage) of the job
   * @return progress
  **/
  @ApiModelProperty(value = "The progress (as a percentage) of the job")
  public Integer getProgress() {
    return progress;
  }

  public void setProgress(Integer progress) {
    this.progress = progress;
  }

  public Job data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * A freeform data field containing additional information about the job
   * @return data
  **/
  @ApiModelProperty(value = "A freeform data field containing additional information about the job")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Job job = (Job) o;
    return Objects.equals(this.id, job.id) &&
        Objects.equals(this.type, job.type) &&
        Objects.equals(this.createAt, job.createAt) &&
        Objects.equals(this.startAt, job.startAt) &&
        Objects.equals(this.lastActivityAt, job.lastActivityAt) &&
        Objects.equals(this.status, job.status) &&
        Objects.equals(this.progress, job.progress) &&
        Objects.equals(this.data, job.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, createAt, startAt, lastActivityAt, status, progress, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    lastActivityAt: ").append(toIndentedString(lastActivityAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

