/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OAuthApp
 */

public class OAuthApp {
  @SerializedName("id")
  private String id = null;

  @SerializedName("client_secret")
  private String clientSecret = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("icon_url")
  private String iconUrl = null;

  @SerializedName("callback_urls")
  private List<String> callbackUrls = null;

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("is_trusted")
  private Boolean isTrusted = null;

  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("update_at")
  private Integer updateAt = null;

  public OAuthApp id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The client id of the application
   * @return id
  **/
  @ApiModelProperty(value = "The client id of the application")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OAuthApp clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * The client secret of the application
   * @return clientSecret
  **/
  @ApiModelProperty(value = "The client secret of the application")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public OAuthApp name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the client application
   * @return name
  **/
  @ApiModelProperty(value = "The name of the client application")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OAuthApp description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A short description of the application
   * @return description
  **/
  @ApiModelProperty(value = "A short description of the application")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OAuthApp iconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * A URL to an icon to display with the application
   * @return iconUrl
  **/
  @ApiModelProperty(value = "A URL to an icon to display with the application")
  public String getIconUrl() {
    return iconUrl;
  }

  public void setIconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
  }

  public OAuthApp callbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
    return this;
  }

  public OAuthApp addCallbackUrlsItem(String callbackUrlsItem) {
    if (this.callbackUrls == null) {
      this.callbackUrls = new ArrayList<String>();
    }
    this.callbackUrls.add(callbackUrlsItem);
    return this;
  }

   /**
   * A list of callback URLs for the appliation
   * @return callbackUrls
  **/
  @ApiModelProperty(value = "A list of callback URLs for the appliation")
  public List<String> getCallbackUrls() {
    return callbackUrls;
  }

  public void setCallbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
  }

  public OAuthApp homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * A link to the website of the application
   * @return homepage
  **/
  @ApiModelProperty(value = "A link to the website of the application")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public OAuthApp isTrusted(Boolean isTrusted) {
    this.isTrusted = isTrusted;
    return this;
  }

   /**
   * Set this to &#x60;true&#x60; to skip asking users for permission
   * @return isTrusted
  **/
  @ApiModelProperty(value = "Set this to `true` to skip asking users for permission")
  public Boolean isIsTrusted() {
    return isTrusted;
  }

  public void setIsTrusted(Boolean isTrusted) {
    this.isTrusted = isTrusted;
  }

  public OAuthApp createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * The time of registration for the application
   * @return createAt
  **/
  @ApiModelProperty(value = "The time of registration for the application")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public OAuthApp updateAt(Integer updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * The last time of update for the application
   * @return updateAt
  **/
  @ApiModelProperty(value = "The last time of update for the application")
  public Integer getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Integer updateAt) {
    this.updateAt = updateAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthApp oauthApp = (OAuthApp) o;
    return Objects.equals(this.id, oauthApp.id) &&
        Objects.equals(this.clientSecret, oauthApp.clientSecret) &&
        Objects.equals(this.name, oauthApp.name) &&
        Objects.equals(this.description, oauthApp.description) &&
        Objects.equals(this.iconUrl, oauthApp.iconUrl) &&
        Objects.equals(this.callbackUrls, oauthApp.callbackUrls) &&
        Objects.equals(this.homepage, oauthApp.homepage) &&
        Objects.equals(this.isTrusted, oauthApp.isTrusted) &&
        Objects.equals(this.createAt, oauthApp.createAt) &&
        Objects.equals(this.updateAt, oauthApp.updateAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientSecret, name, description, iconUrl, callbackUrls, homepage, isTrusted, createAt, updateAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthApp {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("    callbackUrls: ").append(toIndentedString(callbackUrls)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    isTrusted: ").append(toIndentedString(isTrusted)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

