/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OpenGraphArticle;
import io.swagger.client.model.OpenGraphArticleAuthors;
import io.swagger.client.model.OpenGraphAudios;
import io.swagger.client.model.OpenGraphBook;
import io.swagger.client.model.OpenGraphImages;
import io.swagger.client.model.OpenGraphVideos;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OpenGraph metadata of a webpage
 */
@ApiModel(description = "OpenGraph metadata of a webpage")

public class OpenGraph {
  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("determiner")
  private String determiner = null;

  @SerializedName("site_name")
  private String siteName = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("locales_alternate")
  private List<String> localesAlternate = null;

  @SerializedName("images")
  private List<OpenGraphImages> images = null;

  @SerializedName("videos")
  private List<OpenGraphVideos> videos = null;

  @SerializedName("audios")
  private List<OpenGraphAudios> audios = null;

  @SerializedName("article")
  private OpenGraphArticle article = null;

  @SerializedName("book")
  private OpenGraphBook book = null;

  @SerializedName("profile")
  private OpenGraphArticleAuthors profile = null;

  public OpenGraph type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public OpenGraph url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public OpenGraph title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public OpenGraph description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OpenGraph determiner(String determiner) {
    this.determiner = determiner;
    return this;
  }

   /**
   * Get determiner
   * @return determiner
  **/
  @ApiModelProperty(value = "")
  public String getDeterminer() {
    return determiner;
  }

  public void setDeterminer(String determiner) {
    this.determiner = determiner;
  }

  public OpenGraph siteName(String siteName) {
    this.siteName = siteName;
    return this;
  }

   /**
   * Get siteName
   * @return siteName
  **/
  @ApiModelProperty(value = "")
  public String getSiteName() {
    return siteName;
  }

  public void setSiteName(String siteName) {
    this.siteName = siteName;
  }

  public OpenGraph locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @ApiModelProperty(value = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public OpenGraph localesAlternate(List<String> localesAlternate) {
    this.localesAlternate = localesAlternate;
    return this;
  }

  public OpenGraph addLocalesAlternateItem(String localesAlternateItem) {
    if (this.localesAlternate == null) {
      this.localesAlternate = new ArrayList<String>();
    }
    this.localesAlternate.add(localesAlternateItem);
    return this;
  }

   /**
   * Get localesAlternate
   * @return localesAlternate
  **/
  @ApiModelProperty(value = "")
  public List<String> getLocalesAlternate() {
    return localesAlternate;
  }

  public void setLocalesAlternate(List<String> localesAlternate) {
    this.localesAlternate = localesAlternate;
  }

  public OpenGraph images(List<OpenGraphImages> images) {
    this.images = images;
    return this;
  }

  public OpenGraph addImagesItem(OpenGraphImages imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<OpenGraphImages>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @ApiModelProperty(value = "")
  public List<OpenGraphImages> getImages() {
    return images;
  }

  public void setImages(List<OpenGraphImages> images) {
    this.images = images;
  }

  public OpenGraph videos(List<OpenGraphVideos> videos) {
    this.videos = videos;
    return this;
  }

  public OpenGraph addVideosItem(OpenGraphVideos videosItem) {
    if (this.videos == null) {
      this.videos = new ArrayList<OpenGraphVideos>();
    }
    this.videos.add(videosItem);
    return this;
  }

   /**
   * Get videos
   * @return videos
  **/
  @ApiModelProperty(value = "")
  public List<OpenGraphVideos> getVideos() {
    return videos;
  }

  public void setVideos(List<OpenGraphVideos> videos) {
    this.videos = videos;
  }

  public OpenGraph audios(List<OpenGraphAudios> audios) {
    this.audios = audios;
    return this;
  }

  public OpenGraph addAudiosItem(OpenGraphAudios audiosItem) {
    if (this.audios == null) {
      this.audios = new ArrayList<OpenGraphAudios>();
    }
    this.audios.add(audiosItem);
    return this;
  }

   /**
   * Get audios
   * @return audios
  **/
  @ApiModelProperty(value = "")
  public List<OpenGraphAudios> getAudios() {
    return audios;
  }

  public void setAudios(List<OpenGraphAudios> audios) {
    this.audios = audios;
  }

  public OpenGraph article(OpenGraphArticle article) {
    this.article = article;
    return this;
  }

   /**
   * Get article
   * @return article
  **/
  @ApiModelProperty(value = "")
  public OpenGraphArticle getArticle() {
    return article;
  }

  public void setArticle(OpenGraphArticle article) {
    this.article = article;
  }

  public OpenGraph book(OpenGraphBook book) {
    this.book = book;
    return this;
  }

   /**
   * Get book
   * @return book
  **/
  @ApiModelProperty(value = "")
  public OpenGraphBook getBook() {
    return book;
  }

  public void setBook(OpenGraphBook book) {
    this.book = book;
  }

  public OpenGraph profile(OpenGraphArticleAuthors profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  @ApiModelProperty(value = "")
  public OpenGraphArticleAuthors getProfile() {
    return profile;
  }

  public void setProfile(OpenGraphArticleAuthors profile) {
    this.profile = profile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenGraph openGraph = (OpenGraph) o;
    return Objects.equals(this.type, openGraph.type) &&
        Objects.equals(this.url, openGraph.url) &&
        Objects.equals(this.title, openGraph.title) &&
        Objects.equals(this.description, openGraph.description) &&
        Objects.equals(this.determiner, openGraph.determiner) &&
        Objects.equals(this.siteName, openGraph.siteName) &&
        Objects.equals(this.locale, openGraph.locale) &&
        Objects.equals(this.localesAlternate, openGraph.localesAlternate) &&
        Objects.equals(this.images, openGraph.images) &&
        Objects.equals(this.videos, openGraph.videos) &&
        Objects.equals(this.audios, openGraph.audios) &&
        Objects.equals(this.article, openGraph.article) &&
        Objects.equals(this.book, openGraph.book) &&
        Objects.equals(this.profile, openGraph.profile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, url, title, description, determiner, siteName, locale, localesAlternate, images, videos, audios, article, book, profile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenGraph {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    determiner: ").append(toIndentedString(determiner)).append("\n");
    sb.append("    siteName: ").append(toIndentedString(siteName)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    localesAlternate: ").append(toIndentedString(localesAlternate)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    videos: ").append(toIndentedString(videos)).append("\n");
    sb.append("    audios: ").append(toIndentedString(audios)).append("\n");
    sb.append("    article: ").append(toIndentedString(article)).append("\n");
    sb.append("    book: ").append(toIndentedString(book)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

