/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OpenGraphArticleAuthors;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Article object used in OpenGraph metadata of a webpage, if type is article
 */
@ApiModel(description = "Article object used in OpenGraph metadata of a webpage, if type is article")

public class OpenGraphArticle {
  @SerializedName("published_time")
  private String publishedTime = null;

  @SerializedName("modified_time")
  private String modifiedTime = null;

  @SerializedName("expiration_time")
  private String expirationTime = null;

  @SerializedName("section")
  private String section = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("authors")
  private List<OpenGraphArticleAuthors> authors = null;

  public OpenGraphArticle publishedTime(String publishedTime) {
    this.publishedTime = publishedTime;
    return this;
  }

   /**
   * Get publishedTime
   * @return publishedTime
  **/
  @ApiModelProperty(value = "")
  public String getPublishedTime() {
    return publishedTime;
  }

  public void setPublishedTime(String publishedTime) {
    this.publishedTime = publishedTime;
  }

  public OpenGraphArticle modifiedTime(String modifiedTime) {
    this.modifiedTime = modifiedTime;
    return this;
  }

   /**
   * Get modifiedTime
   * @return modifiedTime
  **/
  @ApiModelProperty(value = "")
  public String getModifiedTime() {
    return modifiedTime;
  }

  public void setModifiedTime(String modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  public OpenGraphArticle expirationTime(String expirationTime) {
    this.expirationTime = expirationTime;
    return this;
  }

   /**
   * Get expirationTime
   * @return expirationTime
  **/
  @ApiModelProperty(value = "")
  public String getExpirationTime() {
    return expirationTime;
  }

  public void setExpirationTime(String expirationTime) {
    this.expirationTime = expirationTime;
  }

  public OpenGraphArticle section(String section) {
    this.section = section;
    return this;
  }

   /**
   * Get section
   * @return section
  **/
  @ApiModelProperty(value = "")
  public String getSection() {
    return section;
  }

  public void setSection(String section) {
    this.section = section;
  }

  public OpenGraphArticle tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public OpenGraphArticle addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public OpenGraphArticle authors(List<OpenGraphArticleAuthors> authors) {
    this.authors = authors;
    return this;
  }

  public OpenGraphArticle addAuthorsItem(OpenGraphArticleAuthors authorsItem) {
    if (this.authors == null) {
      this.authors = new ArrayList<OpenGraphArticleAuthors>();
    }
    this.authors.add(authorsItem);
    return this;
  }

   /**
   * Get authors
   * @return authors
  **/
  @ApiModelProperty(value = "")
  public List<OpenGraphArticleAuthors> getAuthors() {
    return authors;
  }

  public void setAuthors(List<OpenGraphArticleAuthors> authors) {
    this.authors = authors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenGraphArticle openGraphArticle = (OpenGraphArticle) o;
    return Objects.equals(this.publishedTime, openGraphArticle.publishedTime) &&
        Objects.equals(this.modifiedTime, openGraphArticle.modifiedTime) &&
        Objects.equals(this.expirationTime, openGraphArticle.expirationTime) &&
        Objects.equals(this.section, openGraphArticle.section) &&
        Objects.equals(this.tags, openGraphArticle.tags) &&
        Objects.equals(this.authors, openGraphArticle.authors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publishedTime, modifiedTime, expirationTime, section, tags, authors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenGraphArticle {\n");
    
    sb.append("    publishedTime: ").append(toIndentedString(publishedTime)).append("\n");
    sb.append("    modifiedTime: ").append(toIndentedString(modifiedTime)).append("\n");
    sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
    sb.append("    section: ").append(toIndentedString(section)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    authors: ").append(toIndentedString(authors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

