/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OutgoingWebhook
 */

public class OutgoingWebhook {
  @SerializedName("id")
  private String id = null;

  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("update_at")
  private Integer updateAt = null;

  @SerializedName("delete_at")
  private Integer deleteAt = null;

  @SerializedName("creator_id")
  private String creatorId = null;

  @SerializedName("team_id")
  private String teamId = null;

  @SerializedName("channel_id")
  private String channelId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("trigger_words")
  private List<String> triggerWords = null;

  @SerializedName("trigger_when")
  private Integer triggerWhen = null;

  @SerializedName("callback_urls")
  private List<String> callbackUrls = null;

  @SerializedName("content_type")
  private String contentType = "application/x-www-form-urlencoded";

  public OutgoingWebhook id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for this outgoing webhook
   * @return id
  **/
  @ApiModelProperty(value = "The unique identifier for this outgoing webhook")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OutgoingWebhook createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * Get createAt
   * @return createAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public OutgoingWebhook updateAt(Integer updateAt) {
    this.updateAt = updateAt;
    return this;
  }

   /**
   * Get updateAt
   * @return updateAt
  **/
  @ApiModelProperty(value = "")
  public Integer getUpdateAt() {
    return updateAt;
  }

  public void setUpdateAt(Integer updateAt) {
    this.updateAt = updateAt;
  }

  public OutgoingWebhook deleteAt(Integer deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * Get deleteAt
   * @return deleteAt
  **/
  @ApiModelProperty(value = "")
  public Integer getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(Integer deleteAt) {
    this.deleteAt = deleteAt;
  }

  public OutgoingWebhook creatorId(String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * The Id of the user who created the webhook
   * @return creatorId
  **/
  @ApiModelProperty(value = "The Id of the user who created the webhook")
  public String getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }

  public OutgoingWebhook teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The ID of the team that the webhook watchs
   * @return teamId
  **/
  @ApiModelProperty(value = "The ID of the team that the webhook watchs")
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public OutgoingWebhook channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The ID of a public channel that the webhook watchs
   * @return channelId
  **/
  @ApiModelProperty(value = "The ID of a public channel that the webhook watchs")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public OutgoingWebhook description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description for this outgoing webhook
   * @return description
  **/
  @ApiModelProperty(value = "The description for this outgoing webhook")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OutgoingWebhook displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name for this outgoing webhook
   * @return displayName
  **/
  @ApiModelProperty(value = "The display name for this outgoing webhook")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OutgoingWebhook triggerWords(List<String> triggerWords) {
    this.triggerWords = triggerWords;
    return this;
  }

  public OutgoingWebhook addTriggerWordsItem(String triggerWordsItem) {
    if (this.triggerWords == null) {
      this.triggerWords = new ArrayList<String>();
    }
    this.triggerWords.add(triggerWordsItem);
    return this;
  }

   /**
   * List of words for the webhook to trigger on
   * @return triggerWords
  **/
  @ApiModelProperty(value = "List of words for the webhook to trigger on")
  public List<String> getTriggerWords() {
    return triggerWords;
  }

  public void setTriggerWords(List<String> triggerWords) {
    this.triggerWords = triggerWords;
  }

  public OutgoingWebhook triggerWhen(Integer triggerWhen) {
    this.triggerWhen = triggerWhen;
    return this;
  }

   /**
   * When to trigger the webhook, &#x60;0&#x60; when a trigger word is present at all and &#x60;1&#x60; if the message starts with a trigger word
   * @return triggerWhen
  **/
  @ApiModelProperty(value = "When to trigger the webhook, `0` when a trigger word is present at all and `1` if the message starts with a trigger word")
  public Integer getTriggerWhen() {
    return triggerWhen;
  }

  public void setTriggerWhen(Integer triggerWhen) {
    this.triggerWhen = triggerWhen;
  }

  public OutgoingWebhook callbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
    return this;
  }

  public OutgoingWebhook addCallbackUrlsItem(String callbackUrlsItem) {
    if (this.callbackUrls == null) {
      this.callbackUrls = new ArrayList<String>();
    }
    this.callbackUrls.add(callbackUrlsItem);
    return this;
  }

   /**
   * The URLs to POST the payloads to when the webhook is triggered
   * @return callbackUrls
  **/
  @ApiModelProperty(value = "The URLs to POST the payloads to when the webhook is triggered")
  public List<String> getCallbackUrls() {
    return callbackUrls;
  }

  public void setCallbackUrls(List<String> callbackUrls) {
    this.callbackUrls = callbackUrls;
  }

  public OutgoingWebhook contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * The format to POST the data in, either &#x60;application/json&#x60; or &#x60;application/x-www-form-urlencoded&#x60;
   * @return contentType
  **/
  @ApiModelProperty(value = "The format to POST the data in, either `application/json` or `application/x-www-form-urlencoded`")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutgoingWebhook outgoingWebhook = (OutgoingWebhook) o;
    return Objects.equals(this.id, outgoingWebhook.id) &&
        Objects.equals(this.createAt, outgoingWebhook.createAt) &&
        Objects.equals(this.updateAt, outgoingWebhook.updateAt) &&
        Objects.equals(this.deleteAt, outgoingWebhook.deleteAt) &&
        Objects.equals(this.creatorId, outgoingWebhook.creatorId) &&
        Objects.equals(this.teamId, outgoingWebhook.teamId) &&
        Objects.equals(this.channelId, outgoingWebhook.channelId) &&
        Objects.equals(this.description, outgoingWebhook.description) &&
        Objects.equals(this.displayName, outgoingWebhook.displayName) &&
        Objects.equals(this.triggerWords, outgoingWebhook.triggerWords) &&
        Objects.equals(this.triggerWhen, outgoingWebhook.triggerWhen) &&
        Objects.equals(this.callbackUrls, outgoingWebhook.callbackUrls) &&
        Objects.equals(this.contentType, outgoingWebhook.contentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createAt, updateAt, deleteAt, creatorId, teamId, channelId, description, displayName, triggerWords, triggerWhen, callbackUrls, contentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutgoingWebhook {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    updateAt: ").append(toIndentedString(updateAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    triggerWords: ").append(toIndentedString(triggerWords)).append("\n");
    sb.append("    triggerWhen: ").append(toIndentedString(triggerWhen)).append("\n");
    sb.append("    callbackUrls: ").append(toIndentedString(callbackUrls)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

