/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SamlCertificateStatus
 */

public class SamlCertificateStatus {
  @SerializedName("idp_certificate_file")
  private Boolean idpCertificateFile = null;

  @SerializedName("public_certificate_file")
  private Boolean publicCertificateFile = null;

  @SerializedName("private_key_file")
  private Boolean privateKeyFile = null;

  public SamlCertificateStatus idpCertificateFile(Boolean idpCertificateFile) {
    this.idpCertificateFile = idpCertificateFile;
    return this;
  }

   /**
   * Status is good when &#x60;true&#x60;
   * @return idpCertificateFile
  **/
  @ApiModelProperty(value = "Status is good when `true`")
  public Boolean isIdpCertificateFile() {
    return idpCertificateFile;
  }

  public void setIdpCertificateFile(Boolean idpCertificateFile) {
    this.idpCertificateFile = idpCertificateFile;
  }

  public SamlCertificateStatus publicCertificateFile(Boolean publicCertificateFile) {
    this.publicCertificateFile = publicCertificateFile;
    return this;
  }

   /**
   * Status is good when &#x60;true&#x60;
   * @return publicCertificateFile
  **/
  @ApiModelProperty(value = "Status is good when `true`")
  public Boolean isPublicCertificateFile() {
    return publicCertificateFile;
  }

  public void setPublicCertificateFile(Boolean publicCertificateFile) {
    this.publicCertificateFile = publicCertificateFile;
  }

  public SamlCertificateStatus privateKeyFile(Boolean privateKeyFile) {
    this.privateKeyFile = privateKeyFile;
    return this;
  }

   /**
   * Status is good when &#x60;true&#x60;
   * @return privateKeyFile
  **/
  @ApiModelProperty(value = "Status is good when `true`")
  public Boolean isPrivateKeyFile() {
    return privateKeyFile;
  }

  public void setPrivateKeyFile(Boolean privateKeyFile) {
    this.privateKeyFile = privateKeyFile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SamlCertificateStatus samlCertificateStatus = (SamlCertificateStatus) o;
    return Objects.equals(this.idpCertificateFile, samlCertificateStatus.idpCertificateFile) &&
        Objects.equals(this.publicCertificateFile, samlCertificateStatus.publicCertificateFile) &&
        Objects.equals(this.privateKeyFile, samlCertificateStatus.privateKeyFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idpCertificateFile, publicCertificateFile, privateKeyFile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SamlCertificateStatus {\n");
    
    sb.append("    idpCertificateFile: ").append(toIndentedString(idpCertificateFile)).append("\n");
    sb.append("    publicCertificateFile: ").append(toIndentedString(publicCertificateFile)).append("\n");
    sb.append("    privateKeyFile: ").append(toIndentedString(privateKeyFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

