/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TeamMember;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Session
 */

public class Session {
  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("expires_at")
  private Integer expiresAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("is_oauth")
  private Boolean isOauth = null;

  @SerializedName("last_activity_at")
  private Integer lastActivityAt = null;

  @SerializedName("props")
  private Object props = null;

  @SerializedName("roles")
  private String roles = null;

  @SerializedName("team_members")
  private List<TeamMember> teamMembers = null;

  @SerializedName("token")
  private String token = null;

  @SerializedName("user_id")
  private String userId = null;

  public Session createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * Get createAt
   * @return createAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public Session deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Session expiresAt(Integer expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @ApiModelProperty(value = "")
  public Integer getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(Integer expiresAt) {
    this.expiresAt = expiresAt;
  }

  public Session id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Session isOauth(Boolean isOauth) {
    this.isOauth = isOauth;
    return this;
  }

   /**
   * Get isOauth
   * @return isOauth
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsOauth() {
    return isOauth;
  }

  public void setIsOauth(Boolean isOauth) {
    this.isOauth = isOauth;
  }

  public Session lastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
    return this;
  }

   /**
   * Get lastActivityAt
   * @return lastActivityAt
  **/
  @ApiModelProperty(value = "")
  public Integer getLastActivityAt() {
    return lastActivityAt;
  }

  public void setLastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
  }

  public Session props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Get props
   * @return props
  **/
  @ApiModelProperty(value = "")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }

  public Session roles(String roles) {
    this.roles = roles;
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public String getRoles() {
    return roles;
  }

  public void setRoles(String roles) {
    this.roles = roles;
  }

  public Session teamMembers(List<TeamMember> teamMembers) {
    this.teamMembers = teamMembers;
    return this;
  }

  public Session addTeamMembersItem(TeamMember teamMembersItem) {
    if (this.teamMembers == null) {
      this.teamMembers = new ArrayList<TeamMember>();
    }
    this.teamMembers.add(teamMembersItem);
    return this;
  }

   /**
   * Get teamMembers
   * @return teamMembers
  **/
  @ApiModelProperty(value = "")
  public List<TeamMember> getTeamMembers() {
    return teamMembers;
  }

  public void setTeamMembers(List<TeamMember> teamMembers) {
    this.teamMembers = teamMembers;
  }

  public Session token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public Session userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Session session = (Session) o;
    return Objects.equals(this.createAt, session.createAt) &&
        Objects.equals(this.deviceId, session.deviceId) &&
        Objects.equals(this.expiresAt, session.expiresAt) &&
        Objects.equals(this.id, session.id) &&
        Objects.equals(this.isOauth, session.isOauth) &&
        Objects.equals(this.lastActivityAt, session.lastActivityAt) &&
        Objects.equals(this.props, session.props) &&
        Objects.equals(this.roles, session.roles) &&
        Objects.equals(this.teamMembers, session.teamMembers) &&
        Objects.equals(this.token, session.token) &&
        Objects.equals(this.userId, session.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createAt, deviceId, expiresAt, id, isOauth, lastActivityAt, props, roles, teamMembers, token, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isOauth: ").append(toIndentedString(isOauth)).append("\n");
    sb.append("    lastActivityAt: ").append(toIndentedString(lastActivityAt)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    teamMembers: ").append(toIndentedString(teamMembers)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

