/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Status
 */

public class Status {
  @SerializedName("user_id")
  private String userId = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("manual")
  private Boolean manual = null;

  @SerializedName("last_activity_at")
  private Integer lastActivityAt = null;

  @SerializedName("active_channel")
  private String activeChannel = null;

  public Status userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public Status status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Status manual(Boolean manual) {
    this.manual = manual;
    return this;
  }

   /**
   * Get manual
   * @return manual
  **/
  @ApiModelProperty(value = "")
  public Boolean isManual() {
    return manual;
  }

  public void setManual(Boolean manual) {
    this.manual = manual;
  }

  public Status lastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
    return this;
  }

   /**
   * Get lastActivityAt
   * @return lastActivityAt
  **/
  @ApiModelProperty(value = "")
  public Integer getLastActivityAt() {
    return lastActivityAt;
  }

  public void setLastActivityAt(Integer lastActivityAt) {
    this.lastActivityAt = lastActivityAt;
  }

  public Status activeChannel(String activeChannel) {
    this.activeChannel = activeChannel;
    return this;
  }

   /**
   * Get activeChannel
   * @return activeChannel
  **/
  @ApiModelProperty(value = "")
  public String getActiveChannel() {
    return activeChannel;
  }

  public void setActiveChannel(String activeChannel) {
    this.activeChannel = activeChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return Objects.equals(this.userId, status.userId) &&
        Objects.equals(this.status, status.status) &&
        Objects.equals(this.manual, status.manual) &&
        Objects.equals(this.lastActivityAt, status.lastActivityAt) &&
        Objects.equals(this.activeChannel, status.activeChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, status, manual, lastActivityAt, activeChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    manual: ").append(toIndentedString(manual)).append("\n");
    sb.append("    lastActivityAt: ").append(toIndentedString(lastActivityAt)).append("\n");
    sb.append("    activeChannel: ").append(toIndentedString(activeChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

