/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.User;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserAutocompleteInChannel
 */

public class UserAutocompleteInChannel {
  @SerializedName("in_channel")
  private List<User> inChannel = null;

  @SerializedName("out_of_channel")
  private List<User> outOfChannel = null;

  public UserAutocompleteInChannel inChannel(List<User> inChannel) {
    this.inChannel = inChannel;
    return this;
  }

  public UserAutocompleteInChannel addInChannelItem(User inChannelItem) {
    if (this.inChannel == null) {
      this.inChannel = new ArrayList<User>();
    }
    this.inChannel.add(inChannelItem);
    return this;
  }

   /**
   * A list of user objects in the channel
   * @return inChannel
  **/
  @ApiModelProperty(value = "A list of user objects in the channel")
  public List<User> getInChannel() {
    return inChannel;
  }

  public void setInChannel(List<User> inChannel) {
    this.inChannel = inChannel;
  }

  public UserAutocompleteInChannel outOfChannel(List<User> outOfChannel) {
    this.outOfChannel = outOfChannel;
    return this;
  }

  public UserAutocompleteInChannel addOutOfChannelItem(User outOfChannelItem) {
    if (this.outOfChannel == null) {
      this.outOfChannel = new ArrayList<User>();
    }
    this.outOfChannel.add(outOfChannelItem);
    return this;
  }

   /**
   * A list of user objects not in the channel
   * @return outOfChannel
  **/
  @ApiModelProperty(value = "A list of user objects not in the channel")
  public List<User> getOutOfChannel() {
    return outOfChannel;
  }

  public void setOutOfChannel(List<User> outOfChannel) {
    this.outOfChannel = outOfChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAutocompleteInChannel userAutocompleteInChannel = (UserAutocompleteInChannel) o;
    return Objects.equals(this.inChannel, userAutocompleteInChannel.inChannel) &&
        Objects.equals(this.outOfChannel, userAutocompleteInChannel.outOfChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inChannel, outOfChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAutocompleteInChannel {\n");
    
    sb.append("    inChannel: ").append(toIndentedString(inChannel)).append("\n");
    sb.append("    outOfChannel: ").append(toIndentedString(outOfChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

