/*
 * Mattermost API Reference
 * ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
 *
 * OpenAPI spec version: 4.0.0
 * Contact: feedback@mattermost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserAuthData
 */

public class UserAuthData {
  @SerializedName("auth_data")
  private String authData = null;

  @SerializedName("auth_service")
  private String authService = null;

  @SerializedName("password")
  private String password = null;

  public UserAuthData authData(String authData) {
    this.authData = authData;
    return this;
  }

   /**
   * Service-specific authentication data
   * @return authData
  **/
  @ApiModelProperty(value = "Service-specific authentication data")
  public String getAuthData() {
    return authData;
  }

  public void setAuthData(String authData) {
    this.authData = authData;
  }

  public UserAuthData authService(String authService) {
    this.authService = authService;
    return this;
  }

   /**
   * The authentication service such as \&quot;email\&quot;, \&quot;gitlab\&quot;, or \&quot;ldap\&quot;
   * @return authService
  **/
  @ApiModelProperty(value = "The authentication service such as \"email\", \"gitlab\", or \"ldap\"")
  public String getAuthService() {
    return authService;
  }

  public void setAuthService(String authService) {
    this.authService = authService;
  }

  public UserAuthData password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The password used for email authentication
   * @return password
  **/
  @ApiModelProperty(value = "The password used for email authentication")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAuthData userAuthData = (UserAuthData) o;
    return Objects.equals(this.authData, userAuthData.authData) &&
        Objects.equals(this.authService, userAuthData.authService) &&
        Objects.equals(this.password, userAuthData.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authData, authService, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAuthData {\n");
    
    sb.append("    authData: ").append(toIndentedString(authData)).append("\n");
    sb.append("    authService: ").append(toIndentedString(authService)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

